# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutoConnectCUMTmini.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import res_rc
from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.account = QtWidgets.QLineEdit(self.centralwidget)
        self.account.setGeometry(QtCore.QRect(80, 20, 115, 21))
        self.account.setObjectName("account")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(80, 60, 115, 21))
        self.password.setObjectName("password")
        self.internet = QtWidgets.QComboBox(self.centralwidget)
        self.internet.setGeometry(QtCore.QRect(80, 100, 111, 22))
        self.internet.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.internet.setObjectName("internet")
        self.internet.addItem("")
        self.internet.addItem("")
        self.internet.addItem("")
        self.internet.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 62, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 62, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 62, 16))
        self.label_3.setObjectName("label_3")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(10, 160, 181, 24))
        self.save.setObjectName("save")
        self.log = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(203, 20, 181, 161))
        self.log.setObjectName("log")
        self.stoptime = QtWidgets.QCheckBox(self.centralwidget)
        self.stoptime.setGeometry(QtCore.QRect(20, 130, 171, 20))
        self.stoptime.setObjectName("stoptime")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 180, 71, 20))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoConnectCUMTmini"))
        self.account.setPlaceholderText(_translate("MainWindow", "account here..."))
        self.password.setPlaceholderText(_translate("MainWindow", "password here..."))
        self.internet.setItemText(0, _translate("MainWindow", "中国移动"))
        self.internet.setItemText(1, _translate("MainWindow", "中国联通"))
        self.internet.setItemText(2, _translate("MainWindow", "中国电信"))
        self.internet.setItemText(3, _translate("MainWindow", "校园网"))
        self.label.setText(_translate("MainWindow", "账号："))
        self.label_2.setText(_translate("MainWindow", "密码："))
        self.label_3.setText(_translate("MainWindow", "运营商："))
        self.save.setText(_translate("MainWindow", "保存"))
        self.stoptime.setText(_translate("MainWindow", "夜间23:25-6:35停止运行"))
        self.label_4.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" text-decoration: underline; color:#333333; vertical-align:sub;\">右键托盘发现更多...</span></p></body></html>"))


